### ISSUE TITLE
Unable to login with Facebook account

### ISSUE THREAD

**Issue by Rodge** [JorritPosthuma/MixCloud-Desktop#13]
Nothing happens when clicking on the button for logging in with Facebook, and trying to log in with email is aborted with the message 

"It looks like you signed up with Facebook - click the Facebook login button instead. Or can add a password by using the Forgot Password link below."

I also tried uninstalling the app with App Cleaner and then log in with email (without trying Facebook login first), same happened.

**Comment by TheSpyder** [comment]
It's just occurred to me that the download hasn't been updated since a fix for this went into the code. I'll try to find time for that soon - in the meantime if you have Xcode installed you can build the app from source and it should work.

**Comment by TheSpyder** [comment]
I have _finally_ published the new build with this. Sorry it slipped through the cracks.

**Comment by repe85** [comment]
Just a Mixcloud listener here, the PC desktop version's facebook login button doesn't work. I stumbled to this site when looking for answer how to fix that. Any possible clue what to do? When I click the facebook login button nothing happens but in my tablet the android version works normally. Thanks and kind Greetings Antti from Finland.

**Comment by TheSpyder** [comment]
This isn't an official client, sorry. The facebook login button was broken for a long time, but the [current build](https://github.com/JorritPosthuma/MixCloud-Desktop/releases/tag/v0.5) should fix that.
