### ISSUE TITLE
MixCloud launched new site version, and some elements look funny

### ISSUE THREAD

**Issue by alexjulien** [JorritPosthuma/MixCloud-Desktop#14]
![captura de pantalla 2017-01-31 a las 14 43 57](https://cloud.githubusercontent.com/assets/17480397/22483657/ca9d03e2-e7c3-11e6-9ab5-78b556f2449c.png)
![captura de pantalla 2017-01-31 a las 14 44 10](https://cloud.githubusercontent.com/assets/17480397/22483661/cc7b1cc6-e7c3-11e6-979d-b2b37824edb4.png)

Check the pause icon off-center.

Keys are working fine, though.

**Comment by TheSpyder** [comment]
It looks ok to me - the app is based around a simple Safari webview, if you log in with Safari do you see the same thing? What version of Safari are you using?

**Comment by alexjulien** [comment]
I have Safari Versión 10.0.3 (10602.4.8.0.1), and it looks well. 
![Safari](https://cloud.githubusercontent.com/assets/17480397/22757323/f0666a8a-ee0f-11e6-9176-7940443135b5.png)

while on the app
![MixCloud Desktop](https://cloud.githubusercontent.com/assets/17480397/22757352/057b0bba-ee10-11e6-965c-854818eb07f4.png)

It's weird, I know. Nothing terrible, though. Other than this cosmetic detail, it's working just fine.

**Comment by askdesigners** [comment]
Ah yes the shitty Safari webview. 

If this wrapper were built in Electron you'd get the much more up to date Chromium webview ;)

**Comment by TheSpyder** [comment]
This app was created before electron became popular. And I'd rather it use Safari anyway.

It's possible the app is doing something to cause this bug, I've actually stopped using it myself now as Safari supports media keys directly.

**Comment by TheSpyder** [comment]
Maybe Apple fixed something, maybe I just needed to recompile, either way it's working fine and I'll have a new build up soon.
