### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by mistapinguin** [JorritPosthuma/MixCloud-Desktop#16]
Heres a new app icon for a new fresh look which is conform to MixCloud CI.
I noted that the icon of this app will be displayed lightly bigger than Icons in other apps. 
Maybe you can fix this in code cause icon size should be correct and is similar to other icons I used on MacOs (High Sierra).

https://www.dropbox.com/s/iivzoehhz2bvs1a/AppIcon.icns?dl=0

Would love to see it in your app :)

**Comment by TheSpyder** [comment]
Ooh thanks for that! I wasn't sure if anyone was still using the app. I'll see if I can update the icon soon.

**Comment by mistapinguin** [comment]
No problem - looking forward to it!
