### ISSUE TITLE
Please provide a build or instructions to build

### ISSUE THREAD

**Issue by Ch00k** [JorritPosthuma/MixCloud-Desktop#3]
Hi!
I'm rather new to OS X  development so I don't know how to build this project. I presume I need XCode installed. It would be greate if you could provide if not the build itself then at least the instructions to build the project from source.
Thanks!

**Comment by highacid** [comment]
Just use the Issued versions
https://github.com/JorritPosthuma/MixCloud-Desktop/releases/download/v0.2/MixCloud.Desktop.zip

**Comment by Ch00k** [comment]
How come I did not notice them earlier... Thanks.
