### ISSUE TITLE
The app does not work on OS X 10.8

### ISSUE THREAD

**Issue by Ch00k** [JorritPosthuma/MixCloud-Desktop#4]
Upon startup it says that it requires 10.9. Is there anything that can be done to make it work on 10.8?

**Comment by davidvb** [comment]
I would like to see it run on 10.10. Actually, do you have a fully compiled version available somewhere? I'm not a developer so I cant even compile it..

**Comment by JorritPosthuma** [comment]
For both, just compiled a new version:
https://github.com/JorritPosthuma/MixCloud-Desktop/releases/tag/v0.3

I have no ways of testing that it works on 10.8. Works fine on 10.10 though.
