### ISSUE TITLE
Media Keys doesn't work in OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by mandrean** [JorritPosthuma/MixCloud-Desktop#5]
The media keys (play/pause/next/previous) don't work.

Maybe SPMediaKeyTap has some issues with Yosemite.

**Comment by TheSpyder** [comment]
Play/pause is working for me on 10.10. I don't think next/previous are handled by the app (there's no obvious UI for those buttons in mixcloud).

Do you have another app open that handles media keys? That could be interfering with the media key tap.

**Comment by TheSpyder** [comment]
Curious - I just downloaded it on 10.9 and the play/pause buttons aren't working. They do in iTunes. I wonder if it only works on 10.10 for me because I have it compiled from source...

**Comment by TheSpyder** [comment]
I've tracked it down!

It seems the app currently requires uninstalling Flash from Safari (remove `/Library/Internet\ Plug-Ins/Flash Player.plugin` and `flashplayer.xpt`. When a media key is pressed, the app looks for a HTML `audio` element to call play/pause on, and mixcloud uses flash when it can. Clearly both @JorritPosthuma and I uninstalled Flash a long time ago :)

I won't have time to implement this until later this week or next week, but I had a poke around the mixcloud JS and once we know it is a flash player (how is yet to be determined) the code to drive the flash player is:

* play/pause state `$('.player-control').hasClass('player-pause')`
* play `$('object')[0].MixcloudPlayer_pause()`
* pause `$('object')[0].MixcloudPlayer_pause()`

However, it may be worth switching the whole thing to not bother checking for the player state and just call `$('.player-control').click()` whenever the media button is pressed. This will simulate a mouse click on mixcloud's button, which is already a toggle. This works for both players - and also before playback starts (which isn't true today, the audio element is created on demand).

**Comment by JorritPosthuma** [comment]
Hi @TheSpyder! That is some nice debugging! If it all works nice, I can even give you access to the repository if you like?

**Comment by TheSpyder** [comment]
My day job is JavaScript in browsers so this was right up my alley :)

Happy to push it directly to the repository after I've tested it if you want to give me access!

**Comment by mandrean** [comment]
Great job @TheSpyder!

**Comment by TheSpyder** [comment]
I've tested it both with and without flash and it seems fine. As an added bonus, I found a 'frame autosave' setting so the app should remember window size now :)

**Comment by TheSpyder** [comment]
@JorritPosthuma do you want me to make the new release with these changes? I've never done a github release before :)

**Comment by JorritPosthuma** [comment]
Yes! That would be great 😊

**Comment by TheSpyder** [comment]
Done. I hope that works, @mandrean please let me know if I've broken something :)
