### ISSUE TITLE
Facebook Login doesn't work

### ISSUE THREAD

**Issue by Spacelapp** [JorritPosthuma/MixCloud-Desktop#6]

**Comment by nofont** [comment]
Any progress on this?

**Comment by JorritPosthuma** [comment]
Have you tried logging in on normal safari first?

**Comment by TheSpyder** [comment]
Fixed by #7

**Comment by akx** [comment]
Oh, hah. I didn't even notice this issue before!

It was just something that annoyed me personally, so I fixed it... :)
