### ISSUE TITLE
Blocked plugin

### ISSUE THREAD

**Issue by alexjulien** [JorritPosthuma/MixCloud-Desktop#9]
Media keys for my MixCloud, on an independent window: just what the doctor recommended! A Fluid app with all its 4 MB won't do that ;)

So I run the app, login to my account, press play, things seem to be going fine, but instead of music, I get this **blocked plugin** message at the bottom left.
![blocked_plugin](https://cloud.githubusercontent.com/assets/17480397/13328798/4c37b50c-dbb6-11e5-815d-b853128e506b.png)

So I check if Safari works (I use Chrome). Mixcloud on Safari works well. Am I doing it wrong? Do I need to do something first?

Thanks.

**Comment by JorritPosthuma** [comment]
Hi! I remember something about having flash installed (for safari). Can you check if that is the case? And if so, if (temporary) disabling it fixes it?

**Comment by alexjulien** [comment]
Hi. I am using 0.4. I have tried both disabling only the Flash module, as well as ALL the modules in Safari. The message disappears in both cases, but I still get no audio. The "loading" spinner keeps on spinning. Do you want me to try/validate something?

**Comment by TheSpyder** [comment]
Blocked plugin usually means something is out of date. Disabling flash might not be enough, you could try deleting it from `/Library/Internet\ Plug-Ins`?

Clicking the text should show something about why it's blocked, although it might require a popup. Which reminds me I haven't done a new release with popup support yet.

**Comment by alexjulien** [comment]
Great! I ran the Flash uninstaller available at https://helpx.adobe.com/flash-player/kb/uninstall-flash-player-mac-os.html and now it works. Since I don't use Safari much, we'll see if I miss it at all.
Thanks!
